// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rockskv.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ErrorCode 错误码
type ErrorCode int32

const (
	ErrorCode_OK                  ErrorCode = 0
	ErrorCode_PARTITION_NOT_FOUND ErrorCode = 1
	ErrorCode_PARTITION_MOVED     ErrorCode = 2
	ErrorCode_KEY_NOT_FOUND       ErrorCode = 3
	ErrorCode_INTERNAL_ERROR      ErrorCode = 4
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	switch x {
	case ErrorCode_OK:
		return "OK"
	case ErrorCode_PARTITION_NOT_FOUND:
		return "PARTITION_NOT_FOUND"
	case ErrorCode_PARTITION_MOVED:
		return "PARTITION_MOVED"
	case ErrorCode_KEY_NOT_FOUND:
		return "KEY_NOT_FOUND"
	case ErrorCode_INTERNAL_ERROR:
		return "INTERNAL_ERROR"
	default:
		return "UNKNOWN"
	}
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return nil
}

func (ErrorCode) Type() protoreflect.EnumType {
	return nil
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// NodeRole 节点角色
type NodeRole int32

const (
	NodeRole_STORAGE  NodeRole = 0
	NodeRole_COMPUTE  NodeRole = 1
	NodeRole_METADATA NodeRole = 2
)

func (x NodeRole) Enum() *NodeRole {
	p := new(NodeRole)
	*p = x
	return p
}

func (x NodeRole) String() string {
	switch x {
	case NodeRole_STORAGE:
		return "STORAGE"
	case NodeRole_COMPUTE:
		return "COMPUTE"
	case NodeRole_METADATA:
		return "METADATA"
	default:
		return "UNKNOWN"
	}
}

func (NodeRole) Descriptor() protoreflect.EnumDescriptor {
	return nil
}

func (NodeRole) Type() protoreflect.EnumType {
	return nil
}

func (x NodeRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// PartitionStatus 分区状态
type PartitionStatus int32

const (
	PartitionStatus_NORMAL        PartitionStatus = 0
	PartitionStatus_MIGRATING_OUT PartitionStatus = 1
	PartitionStatus_MIGRATING_IN  PartitionStatus = 2
	PartitionStatus_OFFLINE       PartitionStatus = 3
)

func (x PartitionStatus) Enum() *PartitionStatus {
	p := new(PartitionStatus)
	*p = x
	return p
}

func (x PartitionStatus) String() string {
	switch x {
	case PartitionStatus_NORMAL:
		return "NORMAL"
	case PartitionStatus_MIGRATING_OUT:
		return "MIGRATING_OUT"
	case PartitionStatus_MIGRATING_IN:
		return "MIGRATING_IN"
	case PartitionStatus_OFFLINE:
		return "OFFLINE"
	default:
		return "UNKNOWN"
	}
}

func (PartitionStatus) Descriptor() protoreflect.EnumDescriptor {
	return nil
}

func (PartitionStatus) Type() protoreflect.EnumType {
	return nil
}

func (x PartitionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// ========== KVService 消息定义 ==========

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
}

func (x *GetRequest) String() string {
	return ""
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*GetRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found bool   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
}

func (x *GetResponse) String() string {
	return ""
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (*GetResponse) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type PutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
}

func (x *PutRequest) String() string {
	return ""
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*PutRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
}

func (x *PutResponse) String() string {
	return ""
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (*PutResponse) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *PutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
}

func (x *DeleteRequest) String() string {
	return ""
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
}

func (x *DeleteResponse) String() string {
	return ""
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type KeyValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Found bool   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
}

func (x *KeyValue) String() string {
	return ""
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	return nil
}

func (*KeyValue) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *KeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyValue) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type BatchGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *BatchGetRequest) Reset() {
	*x = BatchGetRequest{}
}

func (x *BatchGetRequest) String() string {
	return ""
}

func (*BatchGetRequest) ProtoMessage() {}

func (x *BatchGetRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*BatchGetRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *BatchGetRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

type BatchGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*KeyValue `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *BatchGetResponse) Reset() {
	*x = BatchGetResponse{}
}

func (x *BatchGetResponse) String() string {
	return ""
}

func (*BatchGetResponse) ProtoMessage() {}

func (x *BatchGetResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (*BatchGetResponse) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *BatchGetResponse) GetItems() []*KeyValue {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchPutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*KeyValue `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *BatchPutRequest) Reset() {
	*x = BatchPutRequest{}
}

func (x *BatchPutRequest) String() string {
	return ""
}

func (*BatchPutRequest) ProtoMessage() {}

func (x *BatchPutRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*BatchPutRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *BatchPutRequest) GetItems() []*KeyValue {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchPutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Count   int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *BatchPutResponse) Reset() {
	*x = BatchPutResponse{}
}

func (x *BatchPutResponse) String() string {
	return ""
}

func (*BatchPutResponse) ProtoMessage() {}

func (x *BatchPutResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (*BatchPutResponse) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *BatchPutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchPutResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// ========== StorageService 消息定义 ==========

type StorageGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key         []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	PartitionId uint32 `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
}

func (x *StorageGetRequest) Reset() {
	*x = StorageGetRequest{}
}

func (x *StorageGetRequest) String() string {
	return ""
}

func (*StorageGetRequest) ProtoMessage() {}

func (x *StorageGetRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*StorageGetRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *StorageGetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *StorageGetRequest) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

type StorageGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte    `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found bool      `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Error ErrorCode `protobuf:"varint,3,opt,name=error,proto3,enum=rockskv.ErrorCode" json:"error,omitempty"`
}

func (x *StorageGetResponse) Reset() {
	*x = StorageGetResponse{}
}

func (x *StorageGetResponse) String() string {
	return ""
}

func (*StorageGetResponse) ProtoMessage() {}

func (x *StorageGetResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (*StorageGetResponse) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *StorageGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StorageGetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *StorageGetResponse) GetError() ErrorCode {
	if x != nil {
		return x.Error
	}
	return ErrorCode_OK
}

type StoragePutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key         []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value       []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	PartitionId uint32 `protobuf:"varint,3,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
}

func (x *StoragePutRequest) Reset() {
	*x = StoragePutRequest{}
}

func (x *StoragePutRequest) String() string {
	return ""
}

func (*StoragePutRequest) ProtoMessage() {}

func (x *StoragePutRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*StoragePutRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *StoragePutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *StoragePutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StoragePutRequest) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

type StoragePutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   ErrorCode `protobuf:"varint,2,opt,name=error,proto3,enum=rockskv.ErrorCode" json:"error,omitempty"`
}

func (x *StoragePutResponse) Reset() {
	*x = StoragePutResponse{}
}

func (x *StoragePutResponse) String() string {
	return ""
}

func (*StoragePutResponse) ProtoMessage() {}

func (x *StoragePutResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (*StoragePutResponse) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *StoragePutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoragePutResponse) GetError() ErrorCode {
	if x != nil {
		return x.Error
	}
	return ErrorCode_OK
}

type StorageDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key         []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	PartitionId uint32 `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
}

func (x *StorageDeleteRequest) Reset() {
	*x = StorageDeleteRequest{}
}

func (x *StorageDeleteRequest) String() string {
	return ""
}

func (*StorageDeleteRequest) ProtoMessage() {}

func (x *StorageDeleteRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*StorageDeleteRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *StorageDeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *StorageDeleteRequest) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

type StorageDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   ErrorCode `protobuf:"varint,2,opt,name=error,proto3,enum=rockskv.ErrorCode" json:"error,omitempty"`
}

func (x *StorageDeleteResponse) Reset() {
	*x = StorageDeleteResponse{}
}

func (x *StorageDeleteResponse) String() string {
	return ""
}

func (*StorageDeleteResponse) ProtoMessage() {}

func (x *StorageDeleteResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (*StorageDeleteResponse) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *StorageDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StorageDeleteResponse) GetError() ErrorCode {
	if x != nil {
		return x.Error
	}
	return ErrorCode_OK
}

type StorageBatchPutRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items       []*KeyValue `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	PartitionId uint32      `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
}

func (x *StorageBatchPutRequest) Reset() {
	*x = StorageBatchPutRequest{}
}

func (x *StorageBatchPutRequest) String() string {
	return ""
}

func (*StorageBatchPutRequest) ProtoMessage() {}

func (x *StorageBatchPutRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*StorageBatchPutRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *StorageBatchPutRequest) GetItems() []*KeyValue {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *StorageBatchPutRequest) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

type StorageBatchPutResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool      `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Count   int32     `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Error   ErrorCode `protobuf:"varint,3,opt,name=error,proto3,enum=rockskv.ErrorCode" json:"error,omitempty"`
}

func (x *StorageBatchPutResponse) Reset() {
	*x = StorageBatchPutResponse{}
}

func (x *StorageBatchPutResponse) String() string {
	return ""
}

func (*StorageBatchPutResponse) ProtoMessage() {}

func (x *StorageBatchPutResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (*StorageBatchPutResponse) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *StorageBatchPutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StorageBatchPutResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *StorageBatchPutResponse) GetError() ErrorCode {
	if x != nil {
		return x.Error
	}
	return ErrorCode_OK
}

type ExportSSTRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartitionId uint32 `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
}

func (x *ExportSSTRequest) Reset() {
	*x = ExportSSTRequest{}
}

func (x *ExportSSTRequest) String() string {
	return ""
}

func (*ExportSSTRequest) ProtoMessage() {}

func (x *ExportSSTRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*ExportSSTRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *ExportSSTRequest) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

type SSTChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data     []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	IsLast   bool   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
}

func (x *SSTChunk) Reset() {
	*x = SSTChunk{}
}

func (x *SSTChunk) String() string {
	return ""
}

func (*SSTChunk) ProtoMessage() {}

func (x *SSTChunk) ProtoReflect() protoreflect.Message {
	return nil
}

func (*SSTChunk) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *SSTChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SSTChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SSTChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type IngestSSTResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool  `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	KeysIngested int64 `protobuf:"varint,2,opt,name=keys_ingested,json=keysIngested,proto3" json:"keys_ingested,omitempty"`
}

func (x *IngestSSTResponse) Reset() {
	*x = IngestSSTResponse{}
}

func (x *IngestSSTResponse) String() string {
	return ""
}

func (*IngestSSTResponse) ProtoMessage() {}

func (x *IngestSSTResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (*IngestSSTResponse) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *IngestSSTResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IngestSSTResponse) GetKeysIngested() int64 {
	if x != nil {
		return x.KeysIngested
	}
	return 0
}

// ========== MetadataService 消息定义 ==========

type RegisterNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addr   string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Role   NodeRole `protobuf:"varint,3,opt,name=role,proto3,enum=rockskv.NodeRole" json:"role,omitempty"`
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
}

func (x *RegisterNodeRequest) String() string {
	return ""
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RegisterNodeRequest) GetRole() NodeRole {
	if x != nil {
		return x.Role
	}
	return NodeRole_STORAGE
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
}

func (x *RegisterNodeResponse) String() string {
	return ""
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *RegisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
}

func (x *HeartbeatRequest) String() string {
	return ""
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RouteVersion uint64 `protobuf:"varint,2,opt,name=route_version,json=routeVersion,proto3" json:"route_version,omitempty"`
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
}

func (x *HeartbeatResponse) String() string {
	return ""
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetRouteVersion() uint64 {
	if x != nil {
		return x.RouteVersion
	}
	return 0
}

type GetRouteTableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *GetRouteTableRequest) Reset() {
	*x = GetRouteTableRequest{}
}

func (x *GetRouteTableRequest) String() string {
	return ""
}

func (*GetRouteTableRequest) ProtoMessage() {}

func (x *GetRouteTableRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*GetRouteTableRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *GetRouteTableRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetRouteTableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RouteTable *RouteTable `protobuf:"bytes,1,opt,name=route_table,json=routeTable,proto3" json:"route_table,omitempty"`
}

func (x *GetRouteTableResponse) Reset() {
	*x = GetRouteTableResponse{}
}

func (x *GetRouteTableResponse) String() string {
	return ""
}

func (*GetRouteTableResponse) ProtoMessage() {}

func (x *GetRouteTableResponse) ProtoReflect() protoreflect.Message {
	return nil
}

func (*GetRouteTableResponse) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *GetRouteTableResponse) GetRouteTable() *RouteTable {
	if x != nil {
		return x.RouteTable
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
}

func (x *SubscribeRequest) String() string {
	return ""
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	return nil
}

func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *SubscribeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RouteUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version    uint64           `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Partitions []*PartitionInfo `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty"`
}

func (x *RouteUpdate) Reset() {
	*x = RouteUpdate{}
}

func (x *RouteUpdate) String() string {
	return ""
}

func (*RouteUpdate) ProtoMessage() {}

func (x *RouteUpdate) ProtoReflect() protoreflect.Message {
	return nil
}

func (*RouteUpdate) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *RouteUpdate) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RouteUpdate) GetPartitions() []*PartitionInfo {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type RouteTable struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Partitions []*PartitionInfo `protobuf:"bytes,1,rep,name=partitions,proto3" json:"partitions,omitempty"`
	Version    uint64           `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *RouteTable) Reset() {
	*x = RouteTable{}
}

func (x *RouteTable) String() string {
	return ""
}

func (*RouteTable) ProtoMessage() {}

func (x *RouteTable) ProtoReflect() protoreflect.Message {
	return nil
}

func (*RouteTable) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *RouteTable) GetPartitions() []*PartitionInfo {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *RouteTable) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type PartitionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartitionId uint32          `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Primary     string          `protobuf:"bytes,2,opt,name=primary,proto3" json:"primary,omitempty"`
	Replica     string          `protobuf:"bytes,3,opt,name=replica,proto3" json:"replica,omitempty"`
	Status      PartitionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=rockskv.PartitionStatus" json:"status,omitempty"`
}

func (x *PartitionInfo) Reset() {
	*x = PartitionInfo{}
}

func (x *PartitionInfo) String() string {
	return ""
}

func (*PartitionInfo) ProtoMessage() {}

func (x *PartitionInfo) ProtoReflect() protoreflect.Message {
	return nil
}

func (*PartitionInfo) Descriptor() ([]byte, []int) {
	return nil, nil
}

func (x *PartitionInfo) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PartitionInfo) GetPrimary() string {
	if x != nil {
		return x.Primary
	}
	return ""
}

func (x *PartitionInfo) GetReplica() string {
	if x != nil {
		return x.Replica
	}
	return ""
}

func (x *PartitionInfo) GetStatus() PartitionStatus {
	if x != nil {
		return x.Status
	}
	return PartitionStatus_NORMAL
}

var File_rockskv_proto protoreflect.FileDescriptor

func init() {
}

var _ sync.Mutex
var _ reflect.Type
