// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: rockskv.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_OK                  ErrorCode = 0
	ErrorCode_PARTITION_NOT_FOUND ErrorCode = 1
	ErrorCode_PARTITION_MOVED     ErrorCode = 2
	ErrorCode_KEY_NOT_FOUND       ErrorCode = 3
	ErrorCode_INTERNAL_ERROR      ErrorCode = 4
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "OK",
		1: "PARTITION_NOT_FOUND",
		2: "PARTITION_MOVED",
		3: "KEY_NOT_FOUND",
		4: "INTERNAL_ERROR",
	}
	ErrorCode_value = map[string]int32{
		"OK":                  0,
		"PARTITION_NOT_FOUND": 1,
		"PARTITION_MOVED":     2,
		"KEY_NOT_FOUND":       3,
		"INTERNAL_ERROR":      4,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_rockskv_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_rockskv_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{0}
}

type NodeRole int32

const (
	NodeRole_STORAGE  NodeRole = 0
	NodeRole_COMPUTE  NodeRole = 1
	NodeRole_METADATA NodeRole = 2
)

// Enum value maps for NodeRole.
var (
	NodeRole_name = map[int32]string{
		0: "STORAGE",
		1: "COMPUTE",
		2: "METADATA",
	}
	NodeRole_value = map[string]int32{
		"STORAGE":  0,
		"COMPUTE":  1,
		"METADATA": 2,
	}
)

func (x NodeRole) Enum() *NodeRole {
	p := new(NodeRole)
	*p = x
	return p
}

func (x NodeRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeRole) Descriptor() protoreflect.EnumDescriptor {
	return file_rockskv_proto_enumTypes[1].Descriptor()
}

func (NodeRole) Type() protoreflect.EnumType {
	return &file_rockskv_proto_enumTypes[1]
}

func (x NodeRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeRole.Descriptor instead.
func (NodeRole) EnumDescriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{1}
}

type PartitionStatus int32

const (
	PartitionStatus_NORMAL        PartitionStatus = 0
	PartitionStatus_MIGRATING_OUT PartitionStatus = 1
	PartitionStatus_MIGRATING_IN  PartitionStatus = 2
	PartitionStatus_OFFLINE       PartitionStatus = 3
)

// Enum value maps for PartitionStatus.
var (
	PartitionStatus_name = map[int32]string{
		0: "NORMAL",
		1: "MIGRATING_OUT",
		2: "MIGRATING_IN",
		3: "OFFLINE",
	}
	PartitionStatus_value = map[string]int32{
		"NORMAL":        0,
		"MIGRATING_OUT": 1,
		"MIGRATING_IN":  2,
		"OFFLINE":       3,
	}
)

func (x PartitionStatus) Enum() *PartitionStatus {
	p := new(PartitionStatus)
	*p = x
	return p
}

func (x PartitionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PartitionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rockskv_proto_enumTypes[2].Descriptor()
}

func (PartitionStatus) Type() protoreflect.EnumType {
	return &file_rockskv_proto_enumTypes[2]
}

func (x PartitionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PartitionStatus.Descriptor instead.
func (PartitionStatus) EnumDescriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{2}
}

type MigrationState int32

const (
	MigrationState_MIGRATION_NONE      MigrationState = 0
	MigrationState_MIGRATION_PREPARING MigrationState = 1 // Creating snapshot
	MigrationState_MIGRATION_COPYING   MigrationState = 2 // Transferring SST data
	MigrationState_MIGRATION_CATCHUP   MigrationState = 3 // Catching up incremental writes
	MigrationState_MIGRATION_SWITCHING MigrationState = 4 // Switching route
	MigrationState_MIGRATION_COMPLETE  MigrationState = 5 // Migration done
	MigrationState_MIGRATION_FAILED    MigrationState = 6 // Migration failed
)

// Enum value maps for MigrationState.
var (
	MigrationState_name = map[int32]string{
		0: "MIGRATION_NONE",
		1: "MIGRATION_PREPARING",
		2: "MIGRATION_COPYING",
		3: "MIGRATION_CATCHUP",
		4: "MIGRATION_SWITCHING",
		5: "MIGRATION_COMPLETE",
		6: "MIGRATION_FAILED",
	}
	MigrationState_value = map[string]int32{
		"MIGRATION_NONE":      0,
		"MIGRATION_PREPARING": 1,
		"MIGRATION_COPYING":   2,
		"MIGRATION_CATCHUP":   3,
		"MIGRATION_SWITCHING": 4,
		"MIGRATION_COMPLETE":  5,
		"MIGRATION_FAILED":    6,
	}
)

func (x MigrationState) Enum() *MigrationState {
	p := new(MigrationState)
	*p = x
	return p
}

func (x MigrationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MigrationState) Descriptor() protoreflect.EnumDescriptor {
	return file_rockskv_proto_enumTypes[3].Descriptor()
}

func (MigrationState) Type() protoreflect.EnumType {
	return &file_rockskv_proto_enumTypes[3]
}

func (x MigrationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MigrationState.Descriptor instead.
func (MigrationState) EnumDescriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{3}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_rockskv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_rockskv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_rockskv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_rockskv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{3}
}

func (x *PutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_rockskv_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_rockskv_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_rockskv_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{6}
}

func (x *KeyValue) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KeyValue) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyValue) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type BatchGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          [][]byte               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetRequest) Reset() {
	*x = BatchGetRequest{}
	mi := &file_rockskv_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetRequest) ProtoMessage() {}

func (x *BatchGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetRequest.ProtoReflect.Descriptor instead.
func (*BatchGetRequest) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{7}
}

func (x *BatchGetRequest) GetKeys() [][]byte {
	if x != nil {
		return x.Keys
	}
	return nil
}

type BatchGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*KeyValue            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetResponse) Reset() {
	*x = BatchGetResponse{}
	mi := &file_rockskv_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetResponse) ProtoMessage() {}

func (x *BatchGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetResponse.ProtoReflect.Descriptor instead.
func (*BatchGetResponse) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{8}
}

func (x *BatchGetResponse) GetItems() []*KeyValue {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*KeyValue            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPutRequest) Reset() {
	*x = BatchPutRequest{}
	mi := &file_rockskv_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPutRequest) ProtoMessage() {}

func (x *BatchPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPutRequest.ProtoReflect.Descriptor instead.
func (*BatchPutRequest) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{9}
}

func (x *BatchPutRequest) GetItems() []*KeyValue {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchPutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPutResponse) Reset() {
	*x = BatchPutResponse{}
	mi := &file_rockskv_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPutResponse) ProtoMessage() {}

func (x *BatchPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPutResponse.ProtoReflect.Descriptor instead.
func (*BatchPutResponse) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{10}
}

func (x *BatchPutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchPutResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StorageGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	PartitionId   uint32                 `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageGetRequest) Reset() {
	*x = StorageGetRequest{}
	mi := &file_rockskv_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageGetRequest) ProtoMessage() {}

func (x *StorageGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageGetRequest.ProtoReflect.Descriptor instead.
func (*StorageGetRequest) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{11}
}

func (x *StorageGetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *StorageGetRequest) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

type StorageGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	Error         ErrorCode              `protobuf:"varint,3,opt,name=error,proto3,enum=rockskv.ErrorCode" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageGetResponse) Reset() {
	*x = StorageGetResponse{}
	mi := &file_rockskv_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageGetResponse) ProtoMessage() {}

func (x *StorageGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageGetResponse.ProtoReflect.Descriptor instead.
func (*StorageGetResponse) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{12}
}

func (x *StorageGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StorageGetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *StorageGetResponse) GetError() ErrorCode {
	if x != nil {
		return x.Error
	}
	return ErrorCode_OK
}

type StoragePutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	PartitionId   uint32                 `protobuf:"varint,3,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoragePutRequest) Reset() {
	*x = StoragePutRequest{}
	mi := &file_rockskv_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoragePutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoragePutRequest) ProtoMessage() {}

func (x *StoragePutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoragePutRequest.ProtoReflect.Descriptor instead.
func (*StoragePutRequest) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{13}
}

func (x *StoragePutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *StoragePutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StoragePutRequest) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

type StoragePutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         ErrorCode              `protobuf:"varint,2,opt,name=error,proto3,enum=rockskv.ErrorCode" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoragePutResponse) Reset() {
	*x = StoragePutResponse{}
	mi := &file_rockskv_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoragePutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoragePutResponse) ProtoMessage() {}

func (x *StoragePutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoragePutResponse.ProtoReflect.Descriptor instead.
func (*StoragePutResponse) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{14}
}

func (x *StoragePutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoragePutResponse) GetError() ErrorCode {
	if x != nil {
		return x.Error
	}
	return ErrorCode_OK
}

type StorageDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	PartitionId   uint32                 `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageDeleteRequest) Reset() {
	*x = StorageDeleteRequest{}
	mi := &file_rockskv_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDeleteRequest) ProtoMessage() {}

func (x *StorageDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDeleteRequest.ProtoReflect.Descriptor instead.
func (*StorageDeleteRequest) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{15}
}

func (x *StorageDeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *StorageDeleteRequest) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

type StorageDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         ErrorCode              `protobuf:"varint,2,opt,name=error,proto3,enum=rockskv.ErrorCode" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageDeleteResponse) Reset() {
	*x = StorageDeleteResponse{}
	mi := &file_rockskv_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDeleteResponse) ProtoMessage() {}

func (x *StorageDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDeleteResponse.ProtoReflect.Descriptor instead.
func (*StorageDeleteResponse) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{16}
}

func (x *StorageDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StorageDeleteResponse) GetError() ErrorCode {
	if x != nil {
		return x.Error
	}
	return ErrorCode_OK
}

type StorageBatchPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*KeyValue            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	PartitionId   uint32                 `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageBatchPutRequest) Reset() {
	*x = StorageBatchPutRequest{}
	mi := &file_rockskv_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageBatchPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageBatchPutRequest) ProtoMessage() {}

func (x *StorageBatchPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageBatchPutRequest.ProtoReflect.Descriptor instead.
func (*StorageBatchPutRequest) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{17}
}

func (x *StorageBatchPutRequest) GetItems() []*KeyValue {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *StorageBatchPutRequest) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

type StorageBatchPutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Error         ErrorCode              `protobuf:"varint,3,opt,name=error,proto3,enum=rockskv.ErrorCode" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageBatchPutResponse) Reset() {
	*x = StorageBatchPutResponse{}
	mi := &file_rockskv_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageBatchPutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageBatchPutResponse) ProtoMessage() {}

func (x *StorageBatchPutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageBatchPutResponse.ProtoReflect.Descriptor instead.
func (*StorageBatchPutResponse) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{18}
}

func (x *StorageBatchPutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StorageBatchPutResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *StorageBatchPutResponse) GetError() ErrorCode {
	if x != nil {
		return x.Error
	}
	return ErrorCode_OK
}

type ExportSSTRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PartitionId    uint32                 `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	BandwidthLimit int64                  `protobuf:"varint,2,opt,name=bandwidth_limit,json=bandwidthLimit,proto3" json:"bandwidth_limit,omitempty"` // Bytes per second, 0 for unlimited
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExportSSTRequest) Reset() {
	*x = ExportSSTRequest{}
	mi := &file_rockskv_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportSSTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportSSTRequest) ProtoMessage() {}

func (x *ExportSSTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportSSTRequest.ProtoReflect.Descriptor instead.
func (*ExportSSTRequest) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{19}
}

func (x *ExportSSTRequest) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *ExportSSTRequest) GetBandwidthLimit() int64 {
	if x != nil {
		return x.BandwidthLimit
	}
	return 0
}

type SSTChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	PartitionId   uint32                 `protobuf:"varint,4,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	TotalSize     int64                  `protobuf:"varint,5,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"` // Total size of this partition's data
	Offset        int64                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`                        // Current offset for progress tracking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSTChunk) Reset() {
	*x = SSTChunk{}
	mi := &file_rockskv_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSTChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSTChunk) ProtoMessage() {}

func (x *SSTChunk) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSTChunk.ProtoReflect.Descriptor instead.
func (*SSTChunk) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{20}
}

func (x *SSTChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SSTChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SSTChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *SSTChunk) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *SSTChunk) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *SSTChunk) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type IngestSSTResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	KeysIngested  int64                  `protobuf:"varint,2,opt,name=keys_ingested,json=keysIngested,proto3" json:"keys_ingested,omitempty"`
	BytesIngested int64                  `protobuf:"varint,3,opt,name=bytes_ingested,json=bytesIngested,proto3" json:"bytes_ingested,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestSSTResponse) Reset() {
	*x = IngestSSTResponse{}
	mi := &file_rockskv_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestSSTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestSSTResponse) ProtoMessage() {}

func (x *IngestSSTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestSSTResponse.ProtoReflect.Descriptor instead.
func (*IngestSSTResponse) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{21}
}

func (x *IngestSSTResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *IngestSSTResponse) GetKeysIngested() int64 {
	if x != nil {
		return x.KeysIngested
	}
	return 0
}

func (x *IngestSSTResponse) GetBytesIngested() int64 {
	if x != nil {
		return x.BytesIngested
	}
	return 0
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Role          NodeRole               `protobuf:"varint,3,opt,name=role,proto3,enum=rockskv.NodeRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_rockskv_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{22}
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RegisterNodeRequest) GetRole() NodeRole {
	if x != nil {
		return x.Role
	}
	return NodeRole_STORAGE
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_rockskv_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{23}
}

func (x *RegisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_rockskv_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{24}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RouteVersion  uint64                 `protobuf:"varint,2,opt,name=route_version,json=routeVersion,proto3" json:"route_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_rockskv_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{25}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetRouteVersion() uint64 {
	if x != nil {
		return x.RouteVersion
	}
	return 0
}

type GetRouteTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteTableRequest) Reset() {
	*x = GetRouteTableRequest{}
	mi := &file_rockskv_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteTableRequest) ProtoMessage() {}

func (x *GetRouteTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteTableRequest.ProtoReflect.Descriptor instead.
func (*GetRouteTableRequest) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{26}
}

func (x *GetRouteTableRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetRouteTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteTable    *RouteTable            `protobuf:"bytes,1,opt,name=route_table,json=routeTable,proto3" json:"route_table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteTableResponse) Reset() {
	*x = GetRouteTableResponse{}
	mi := &file_rockskv_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteTableResponse) ProtoMessage() {}

func (x *GetRouteTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteTableResponse.ProtoReflect.Descriptor instead.
func (*GetRouteTableResponse) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{27}
}

func (x *GetRouteTableResponse) GetRouteTable() *RouteTable {
	if x != nil {
		return x.RouteTable
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_rockskv_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{28}
}

func (x *SubscribeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RouteUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint64                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Partitions    []*PartitionInfo       `protobuf:"bytes,2,rep,name=partitions,proto3" json:"partitions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteUpdate) Reset() {
	*x = RouteUpdate{}
	mi := &file_rockskv_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteUpdate) ProtoMessage() {}

func (x *RouteUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteUpdate.ProtoReflect.Descriptor instead.
func (*RouteUpdate) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{29}
}

func (x *RouteUpdate) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *RouteUpdate) GetPartitions() []*PartitionInfo {
	if x != nil {
		return x.Partitions
	}
	return nil
}

type RouteTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partitions    []*PartitionInfo       `protobuf:"bytes,1,rep,name=partitions,proto3" json:"partitions,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteTable) Reset() {
	*x = RouteTable{}
	mi := &file_rockskv_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTable) ProtoMessage() {}

func (x *RouteTable) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTable.ProtoReflect.Descriptor instead.
func (*RouteTable) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{30}
}

func (x *RouteTable) GetPartitions() []*PartitionInfo {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *RouteTable) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type PartitionInfo struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PartitionId uint32                 `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	Primary     string                 `protobuf:"bytes,2,opt,name=primary,proto3" json:"primary,omitempty"`
	Replica     string                 `protobuf:"bytes,3,opt,name=replica,proto3" json:"replica,omitempty"`
	Status      PartitionStatus        `protobuf:"varint,4,opt,name=status,proto3,enum=rockskv.PartitionStatus" json:"status,omitempty"`
	// Migration fields
	MigrationTarget string         `protobuf:"bytes,5,opt,name=migration_target,json=migrationTarget,proto3" json:"migration_target,omitempty"` // Target node during migration
	MigrationState  MigrationState `protobuf:"varint,6,opt,name=migration_state,json=migrationState,proto3,enum=rockskv.MigrationState" json:"migration_state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PartitionInfo) Reset() {
	*x = PartitionInfo{}
	mi := &file_rockskv_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionInfo) ProtoMessage() {}

func (x *PartitionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionInfo.ProtoReflect.Descriptor instead.
func (*PartitionInfo) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{31}
}

func (x *PartitionInfo) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PartitionInfo) GetPrimary() string {
	if x != nil {
		return x.Primary
	}
	return ""
}

func (x *PartitionInfo) GetReplica() string {
	if x != nil {
		return x.Replica
	}
	return ""
}

func (x *PartitionInfo) GetStatus() PartitionStatus {
	if x != nil {
		return x.Status
	}
	return PartitionStatus_NORMAL
}

func (x *PartitionInfo) GetMigrationTarget() string {
	if x != nil {
		return x.MigrationTarget
	}
	return ""
}

func (x *PartitionInfo) GetMigrationState() MigrationState {
	if x != nil {
		return x.MigrationState
	}
	return MigrationState_MIGRATION_NONE
}

type TriggerRebalanceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Force          bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`                                         // Force rebalance even if already balanced
	BandwidthLimit int64                  `protobuf:"varint,2,opt,name=bandwidth_limit,json=bandwidthLimit,proto3" json:"bandwidth_limit,omitempty"` // Bytes per second, 0 for default
	MaxConcurrent  int32                  `protobuf:"varint,3,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`    // Max concurrent partition migrations, 0 for default
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TriggerRebalanceRequest) Reset() {
	*x = TriggerRebalanceRequest{}
	mi := &file_rockskv_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRebalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRebalanceRequest) ProtoMessage() {}

func (x *TriggerRebalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRebalanceRequest.ProtoReflect.Descriptor instead.
func (*TriggerRebalanceRequest) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{32}
}

func (x *TriggerRebalanceRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

func (x *TriggerRebalanceRequest) GetBandwidthLimit() int64 {
	if x != nil {
		return x.BandwidthLimit
	}
	return 0
}

func (x *TriggerRebalanceRequest) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

type TriggerRebalanceResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message             string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MigrationId         string                 `protobuf:"bytes,3,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	PartitionsToMigrate int32                  `protobuf:"varint,4,opt,name=partitions_to_migrate,json=partitionsToMigrate,proto3" json:"partitions_to_migrate,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TriggerRebalanceResponse) Reset() {
	*x = TriggerRebalanceResponse{}
	mi := &file_rockskv_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRebalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRebalanceResponse) ProtoMessage() {}

func (x *TriggerRebalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRebalanceResponse.ProtoReflect.Descriptor instead.
func (*TriggerRebalanceResponse) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{33}
}

func (x *TriggerRebalanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerRebalanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TriggerRebalanceResponse) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

func (x *TriggerRebalanceResponse) GetPartitionsToMigrate() int32 {
	if x != nil {
		return x.PartitionsToMigrate
	}
	return 0
}

type GetMigrationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationId   string                 `protobuf:"bytes,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"` // Empty for current migration
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMigrationStatusRequest) Reset() {
	*x = GetMigrationStatusRequest{}
	mi := &file_rockskv_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMigrationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationStatusRequest) ProtoMessage() {}

func (x *GetMigrationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetMigrationStatusRequest) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{34}
}

func (x *GetMigrationStatusRequest) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

type GetMigrationStatusResponse struct {
	state                     protoimpl.MessageState      `protogen:"open.v1"`
	InProgress                bool                        `protobuf:"varint,1,opt,name=in_progress,json=inProgress,proto3" json:"in_progress,omitempty"`
	MigrationId               string                      `protobuf:"bytes,2,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	StartTime                 int64                       `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	TotalPartitions           int32                       `protobuf:"varint,4,opt,name=total_partitions,json=totalPartitions,proto3" json:"total_partitions,omitempty"`
	CompletedPartitions       int32                       `protobuf:"varint,5,opt,name=completed_partitions,json=completedPartitions,proto3" json:"completed_partitions,omitempty"`
	FailedPartitions          int32                       `protobuf:"varint,6,opt,name=failed_partitions,json=failedPartitions,proto3" json:"failed_partitions,omitempty"`
	BytesCopied               int64                       `protobuf:"varint,7,opt,name=bytes_copied,json=bytesCopied,proto3" json:"bytes_copied,omitempty"`
	BytesTotal                int64                       `protobuf:"varint,8,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`
	ProgressPercent           float64                     `protobuf:"fixed64,9,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	EstimatedRemainingSeconds int64                       `protobuf:"varint,10,opt,name=estimated_remaining_seconds,json=estimatedRemainingSeconds,proto3" json:"estimated_remaining_seconds,omitempty"`
	PartitionStatus           []*PartitionMigrationStatus `protobuf:"bytes,11,rep,name=partition_status,json=partitionStatus,proto3" json:"partition_status,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GetMigrationStatusResponse) Reset() {
	*x = GetMigrationStatusResponse{}
	mi := &file_rockskv_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMigrationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMigrationStatusResponse) ProtoMessage() {}

func (x *GetMigrationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMigrationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetMigrationStatusResponse) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{35}
}

func (x *GetMigrationStatusResponse) GetInProgress() bool {
	if x != nil {
		return x.InProgress
	}
	return false
}

func (x *GetMigrationStatusResponse) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

func (x *GetMigrationStatusResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GetMigrationStatusResponse) GetTotalPartitions() int32 {
	if x != nil {
		return x.TotalPartitions
	}
	return 0
}

func (x *GetMigrationStatusResponse) GetCompletedPartitions() int32 {
	if x != nil {
		return x.CompletedPartitions
	}
	return 0
}

func (x *GetMigrationStatusResponse) GetFailedPartitions() int32 {
	if x != nil {
		return x.FailedPartitions
	}
	return 0
}

func (x *GetMigrationStatusResponse) GetBytesCopied() int64 {
	if x != nil {
		return x.BytesCopied
	}
	return 0
}

func (x *GetMigrationStatusResponse) GetBytesTotal() int64 {
	if x != nil {
		return x.BytesTotal
	}
	return 0
}

func (x *GetMigrationStatusResponse) GetProgressPercent() float64 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *GetMigrationStatusResponse) GetEstimatedRemainingSeconds() int64 {
	if x != nil {
		return x.EstimatedRemainingSeconds
	}
	return 0
}

func (x *GetMigrationStatusResponse) GetPartitionStatus() []*PartitionMigrationStatus {
	if x != nil {
		return x.PartitionStatus
	}
	return nil
}

type PartitionMigrationStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PartitionId     uint32                 `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	SourceNode      string                 `protobuf:"bytes,2,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	TargetNode      string                 `protobuf:"bytes,3,opt,name=target_node,json=targetNode,proto3" json:"target_node,omitempty"`
	State           MigrationState         `protobuf:"varint,4,opt,name=state,proto3,enum=rockskv.MigrationState" json:"state,omitempty"`
	BytesCopied     int64                  `protobuf:"varint,5,opt,name=bytes_copied,json=bytesCopied,proto3" json:"bytes_copied,omitempty"`
	BytesTotal      int64                  `protobuf:"varint,6,opt,name=bytes_total,json=bytesTotal,proto3" json:"bytes_total,omitempty"`
	ProgressPercent float64                `protobuf:"fixed64,7,opt,name=progress_percent,json=progressPercent,proto3" json:"progress_percent,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,8,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PartitionMigrationStatus) Reset() {
	*x = PartitionMigrationStatus{}
	mi := &file_rockskv_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionMigrationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionMigrationStatus) ProtoMessage() {}

func (x *PartitionMigrationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionMigrationStatus.ProtoReflect.Descriptor instead.
func (*PartitionMigrationStatus) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{36}
}

func (x *PartitionMigrationStatus) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PartitionMigrationStatus) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

func (x *PartitionMigrationStatus) GetTargetNode() string {
	if x != nil {
		return x.TargetNode
	}
	return ""
}

func (x *PartitionMigrationStatus) GetState() MigrationState {
	if x != nil {
		return x.State
	}
	return MigrationState_MIGRATION_NONE
}

func (x *PartitionMigrationStatus) GetBytesCopied() int64 {
	if x != nil {
		return x.BytesCopied
	}
	return 0
}

func (x *PartitionMigrationStatus) GetBytesTotal() int64 {
	if x != nil {
		return x.BytesTotal
	}
	return 0
}

func (x *PartitionMigrationStatus) GetProgressPercent() float64 {
	if x != nil {
		return x.ProgressPercent
	}
	return 0
}

func (x *PartitionMigrationStatus) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CancelMigrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MigrationId   string                 `protobuf:"bytes,1,opt,name=migration_id,json=migrationId,proto3" json:"migration_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMigrationRequest) Reset() {
	*x = CancelMigrationRequest{}
	mi := &file_rockskv_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMigrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMigrationRequest) ProtoMessage() {}

func (x *CancelMigrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMigrationRequest.ProtoReflect.Descriptor instead.
func (*CancelMigrationRequest) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{37}
}

func (x *CancelMigrationRequest) GetMigrationId() string {
	if x != nil {
		return x.MigrationId
	}
	return ""
}

type CancelMigrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMigrationResponse) Reset() {
	*x = CancelMigrationResponse{}
	mi := &file_rockskv_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMigrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMigrationResponse) ProtoMessage() {}

func (x *CancelMigrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rockskv_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMigrationResponse.ProtoReflect.Descriptor instead.
func (*CancelMigrationResponse) Descriptor() ([]byte, []int) {
	return file_rockskv_proto_rawDescGZIP(), []int{38}
}

func (x *CancelMigrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelMigrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rockskv_proto protoreflect.FileDescriptor

const file_rockskv_proto_rawDesc = "" +
	"\n" +
	"\rrockskv.proto\x12\arockskv\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"4\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"'\n" +
	"\vPutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"H\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"%\n" +
	"\x0fBatchGetRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\fR\x04keys\";\n" +
	"\x10BatchGetResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.rockskv.KeyValueR\x05items\":\n" +
	"\x0fBatchPutRequest\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.rockskv.KeyValueR\x05items\"B\n" +
	"\x10BatchPutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"H\n" +
	"\x11StorageGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12!\n" +
	"\fpartition_id\x18\x02 \x01(\rR\vpartitionId\"j\n" +
	"\x12StorageGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\x12(\n" +
	"\x05error\x18\x03 \x01(\x0e2\x12.rockskv.ErrorCodeR\x05error\"^\n" +
	"\x11StoragePutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12!\n" +
	"\fpartition_id\x18\x03 \x01(\rR\vpartitionId\"X\n" +
	"\x12StoragePutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12(\n" +
	"\x05error\x18\x02 \x01(\x0e2\x12.rockskv.ErrorCodeR\x05error\"K\n" +
	"\x14StorageDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12!\n" +
	"\fpartition_id\x18\x02 \x01(\rR\vpartitionId\"[\n" +
	"\x15StorageDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12(\n" +
	"\x05error\x18\x02 \x01(\x0e2\x12.rockskv.ErrorCodeR\x05error\"d\n" +
	"\x16StorageBatchPutRequest\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.rockskv.KeyValueR\x05items\x12!\n" +
	"\fpartition_id\x18\x02 \x01(\rR\vpartitionId\"s\n" +
	"\x17StorageBatchPutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12(\n" +
	"\x05error\x18\x03 \x01(\x0e2\x12.rockskv.ErrorCodeR\x05error\"^\n" +
	"\x10ExportSSTRequest\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\rR\vpartitionId\x12'\n" +
	"\x0fbandwidth_limit\x18\x02 \x01(\x03R\x0ebandwidthLimit\"\xad\x01\n" +
	"\bSSTChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\x12!\n" +
	"\fpartition_id\x18\x04 \x01(\rR\vpartitionId\x12\x1d\n" +
	"\n" +
	"total_size\x18\x05 \x01(\x03R\ttotalSize\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x03R\x06offset\"y\n" +
	"\x11IngestSSTResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rkeys_ingested\x18\x02 \x01(\x03R\fkeysIngested\x12%\n" +
	"\x0ebytes_ingested\x18\x03 \x01(\x03R\rbytesIngested\"i\n" +
	"\x13RegisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12%\n" +
	"\x04role\x18\x03 \x01(\x0e2\x11.rockskv.NodeRoleR\x04role\"0\n" +
	"\x14RegisterNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"+\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"R\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rroute_version\x18\x02 \x01(\x04R\frouteVersion\"0\n" +
	"\x14GetRouteTableRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\"M\n" +
	"\x15GetRouteTableResponse\x124\n" +
	"\vroute_table\x18\x01 \x01(\v2\x13.rockskv.RouteTableR\n" +
	"routeTable\"+\n" +
	"\x10SubscribeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"_\n" +
	"\vRouteUpdate\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x04R\aversion\x126\n" +
	"\n" +
	"partitions\x18\x02 \x03(\v2\x16.rockskv.PartitionInfoR\n" +
	"partitions\"^\n" +
	"\n" +
	"RouteTable\x126\n" +
	"\n" +
	"partitions\x18\x01 \x03(\v2\x16.rockskv.PartitionInfoR\n" +
	"partitions\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\"\x85\x02\n" +
	"\rPartitionInfo\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\rR\vpartitionId\x12\x18\n" +
	"\aprimary\x18\x02 \x01(\tR\aprimary\x12\x18\n" +
	"\areplica\x18\x03 \x01(\tR\areplica\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.rockskv.PartitionStatusR\x06status\x12)\n" +
	"\x10migration_target\x18\x05 \x01(\tR\x0fmigrationTarget\x12@\n" +
	"\x0fmigration_state\x18\x06 \x01(\x0e2\x17.rockskv.MigrationStateR\x0emigrationState\"\x7f\n" +
	"\x17TriggerRebalanceRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force\x12'\n" +
	"\x0fbandwidth_limit\x18\x02 \x01(\x03R\x0ebandwidthLimit\x12%\n" +
	"\x0emax_concurrent\x18\x03 \x01(\x05R\rmaxConcurrent\"\xa5\x01\n" +
	"\x18TriggerRebalanceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12!\n" +
	"\fmigration_id\x18\x03 \x01(\tR\vmigrationId\x122\n" +
	"\x15partitions_to_migrate\x18\x04 \x01(\x05R\x13partitionsToMigrate\">\n" +
	"\x19GetMigrationStatusRequest\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\tR\vmigrationId\"\x87\x04\n" +
	"\x1aGetMigrationStatusResponse\x12\x1f\n" +
	"\vin_progress\x18\x01 \x01(\bR\n" +
	"inProgress\x12!\n" +
	"\fmigration_id\x18\x02 \x01(\tR\vmigrationId\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12)\n" +
	"\x10total_partitions\x18\x04 \x01(\x05R\x0ftotalPartitions\x121\n" +
	"\x14completed_partitions\x18\x05 \x01(\x05R\x13completedPartitions\x12+\n" +
	"\x11failed_partitions\x18\x06 \x01(\x05R\x10failedPartitions\x12!\n" +
	"\fbytes_copied\x18\a \x01(\x03R\vbytesCopied\x12\x1f\n" +
	"\vbytes_total\x18\b \x01(\x03R\n" +
	"bytesTotal\x12)\n" +
	"\x10progress_percent\x18\t \x01(\x01R\x0fprogressPercent\x12>\n" +
	"\x1bestimated_remaining_seconds\x18\n" +
	" \x01(\x03R\x19estimatedRemainingSeconds\x12L\n" +
	"\x10partition_status\x18\v \x03(\v2!.rockskv.PartitionMigrationStatusR\x0fpartitionStatus\"\xc2\x02\n" +
	"\x18PartitionMigrationStatus\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\rR\vpartitionId\x12\x1f\n" +
	"\vsource_node\x18\x02 \x01(\tR\n" +
	"sourceNode\x12\x1f\n" +
	"\vtarget_node\x18\x03 \x01(\tR\n" +
	"targetNode\x12-\n" +
	"\x05state\x18\x04 \x01(\x0e2\x17.rockskv.MigrationStateR\x05state\x12!\n" +
	"\fbytes_copied\x18\x05 \x01(\x03R\vbytesCopied\x12\x1f\n" +
	"\vbytes_total\x18\x06 \x01(\x03R\n" +
	"bytesTotal\x12)\n" +
	"\x10progress_percent\x18\a \x01(\x01R\x0fprogressPercent\x12#\n" +
	"\rerror_message\x18\b \x01(\tR\ferrorMessage\";\n" +
	"\x16CancelMigrationRequest\x12!\n" +
	"\fmigration_id\x18\x01 \x01(\tR\vmigrationId\"M\n" +
	"\x17CancelMigrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*h\n" +
	"\tErrorCode\x12\x06\n" +
	"\x02OK\x10\x00\x12\x17\n" +
	"\x13PARTITION_NOT_FOUND\x10\x01\x12\x13\n" +
	"\x0fPARTITION_MOVED\x10\x02\x12\x11\n" +
	"\rKEY_NOT_FOUND\x10\x03\x12\x12\n" +
	"\x0eINTERNAL_ERROR\x10\x04*2\n" +
	"\bNodeRole\x12\v\n" +
	"\aSTORAGE\x10\x00\x12\v\n" +
	"\aCOMPUTE\x10\x01\x12\f\n" +
	"\bMETADATA\x10\x02*O\n" +
	"\x0fPartitionStatus\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x00\x12\x11\n" +
	"\rMIGRATING_OUT\x10\x01\x12\x10\n" +
	"\fMIGRATING_IN\x10\x02\x12\v\n" +
	"\aOFFLINE\x10\x03*\xb2\x01\n" +
	"\x0eMigrationState\x12\x12\n" +
	"\x0eMIGRATION_NONE\x10\x00\x12\x17\n" +
	"\x13MIGRATION_PREPARING\x10\x01\x12\x15\n" +
	"\x11MIGRATION_COPYING\x10\x02\x12\x15\n" +
	"\x11MIGRATION_CATCHUP\x10\x03\x12\x17\n" +
	"\x13MIGRATION_SWITCHING\x10\x04\x12\x16\n" +
	"\x12MIGRATION_COMPLETE\x10\x05\x12\x14\n" +
	"\x10MIGRATION_FAILED\x10\x062\xac\x02\n" +
	"\tKVService\x120\n" +
	"\x03Get\x12\x13.rockskv.GetRequest\x1a\x14.rockskv.GetResponse\x120\n" +
	"\x03Put\x12\x13.rockskv.PutRequest\x1a\x14.rockskv.PutResponse\x129\n" +
	"\x06Delete\x12\x16.rockskv.DeleteRequest\x1a\x17.rockskv.DeleteResponse\x12?\n" +
	"\bBatchGet\x12\x18.rockskv.BatchGetRequest\x1a\x19.rockskv.BatchGetResponse\x12?\n" +
	"\bBatchPut\x12\x18.rockskv.BatchPutRequest\x1a\x19.rockskv.BatchPutResponse2\xa3\x03\n" +
	"\x0eStorageService\x12>\n" +
	"\x03Get\x12\x1a.rockskv.StorageGetRequest\x1a\x1b.rockskv.StorageGetResponse\x12>\n" +
	"\x03Put\x12\x1a.rockskv.StoragePutRequest\x1a\x1b.rockskv.StoragePutResponse\x12G\n" +
	"\x06Delete\x12\x1d.rockskv.StorageDeleteRequest\x1a\x1e.rockskv.StorageDeleteResponse\x12M\n" +
	"\bBatchPut\x12\x1f.rockskv.StorageBatchPutRequest\x1a .rockskv.StorageBatchPutResponse\x12;\n" +
	"\tExportSST\x12\x19.rockskv.ExportSSTRequest\x1a\x11.rockskv.SSTChunk0\x01\x12<\n" +
	"\tIngestSST\x12\x11.rockskv.SSTChunk\x1a\x1a.rockskv.IngestSSTResponse(\x012\xcc\x04\n" +
	"\x0fMetadataService\x12K\n" +
	"\fRegisterNode\x12\x1c.rockskv.RegisterNodeRequest\x1a\x1d.rockskv.RegisterNodeResponse\x12B\n" +
	"\tHeartbeat\x12\x19.rockskv.HeartbeatRequest\x1a\x1a.rockskv.HeartbeatResponse\x12N\n" +
	"\rGetRouteTable\x12\x1d.rockskv.GetRouteTableRequest\x1a\x1e.rockskv.GetRouteTableResponse\x12J\n" +
	"\x15SubscribeRouteUpdates\x12\x19.rockskv.SubscribeRequest\x1a\x14.rockskv.RouteUpdate0\x01\x12W\n" +
	"\x10TriggerRebalance\x12 .rockskv.TriggerRebalanceRequest\x1a!.rockskv.TriggerRebalanceResponse\x12]\n" +
	"\x12GetMigrationStatus\x12\".rockskv.GetMigrationStatusRequest\x1a#.rockskv.GetMigrationStatusResponse\x12T\n" +
	"\x0fCancelMigration\x12\x1f.rockskv.CancelMigrationRequest\x1a .rockskv.CancelMigrationResponseB&Z$github.com/winewei/rockskv/pkg/protob\x06proto3"

var (
	file_rockskv_proto_rawDescOnce sync.Once
	file_rockskv_proto_rawDescData []byte
)

func file_rockskv_proto_rawDescGZIP() []byte {
	file_rockskv_proto_rawDescOnce.Do(func() {
		file_rockskv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rockskv_proto_rawDesc), len(file_rockskv_proto_rawDesc)))
	})
	return file_rockskv_proto_rawDescData
}

var file_rockskv_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_rockskv_proto_msgTypes = make([]protoimpl.MessageInfo, 39)
var file_rockskv_proto_goTypes = []any{
	(ErrorCode)(0),                     // 0: rockskv.ErrorCode
	(NodeRole)(0),                      // 1: rockskv.NodeRole
	(PartitionStatus)(0),               // 2: rockskv.PartitionStatus
	(MigrationState)(0),                // 3: rockskv.MigrationState
	(*GetRequest)(nil),                 // 4: rockskv.GetRequest
	(*GetResponse)(nil),                // 5: rockskv.GetResponse
	(*PutRequest)(nil),                 // 6: rockskv.PutRequest
	(*PutResponse)(nil),                // 7: rockskv.PutResponse
	(*DeleteRequest)(nil),              // 8: rockskv.DeleteRequest
	(*DeleteResponse)(nil),             // 9: rockskv.DeleteResponse
	(*KeyValue)(nil),                   // 10: rockskv.KeyValue
	(*BatchGetRequest)(nil),            // 11: rockskv.BatchGetRequest
	(*BatchGetResponse)(nil),           // 12: rockskv.BatchGetResponse
	(*BatchPutRequest)(nil),            // 13: rockskv.BatchPutRequest
	(*BatchPutResponse)(nil),           // 14: rockskv.BatchPutResponse
	(*StorageGetRequest)(nil),          // 15: rockskv.StorageGetRequest
	(*StorageGetResponse)(nil),         // 16: rockskv.StorageGetResponse
	(*StoragePutRequest)(nil),          // 17: rockskv.StoragePutRequest
	(*StoragePutResponse)(nil),         // 18: rockskv.StoragePutResponse
	(*StorageDeleteRequest)(nil),       // 19: rockskv.StorageDeleteRequest
	(*StorageDeleteResponse)(nil),      // 20: rockskv.StorageDeleteResponse
	(*StorageBatchPutRequest)(nil),     // 21: rockskv.StorageBatchPutRequest
	(*StorageBatchPutResponse)(nil),    // 22: rockskv.StorageBatchPutResponse
	(*ExportSSTRequest)(nil),           // 23: rockskv.ExportSSTRequest
	(*SSTChunk)(nil),                   // 24: rockskv.SSTChunk
	(*IngestSSTResponse)(nil),          // 25: rockskv.IngestSSTResponse
	(*RegisterNodeRequest)(nil),        // 26: rockskv.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),       // 27: rockskv.RegisterNodeResponse
	(*HeartbeatRequest)(nil),           // 28: rockskv.HeartbeatRequest
	(*HeartbeatResponse)(nil),          // 29: rockskv.HeartbeatResponse
	(*GetRouteTableRequest)(nil),       // 30: rockskv.GetRouteTableRequest
	(*GetRouteTableResponse)(nil),      // 31: rockskv.GetRouteTableResponse
	(*SubscribeRequest)(nil),           // 32: rockskv.SubscribeRequest
	(*RouteUpdate)(nil),                // 33: rockskv.RouteUpdate
	(*RouteTable)(nil),                 // 34: rockskv.RouteTable
	(*PartitionInfo)(nil),              // 35: rockskv.PartitionInfo
	(*TriggerRebalanceRequest)(nil),    // 36: rockskv.TriggerRebalanceRequest
	(*TriggerRebalanceResponse)(nil),   // 37: rockskv.TriggerRebalanceResponse
	(*GetMigrationStatusRequest)(nil),  // 38: rockskv.GetMigrationStatusRequest
	(*GetMigrationStatusResponse)(nil), // 39: rockskv.GetMigrationStatusResponse
	(*PartitionMigrationStatus)(nil),   // 40: rockskv.PartitionMigrationStatus
	(*CancelMigrationRequest)(nil),     // 41: rockskv.CancelMigrationRequest
	(*CancelMigrationResponse)(nil),    // 42: rockskv.CancelMigrationResponse
}
var file_rockskv_proto_depIdxs = []int32{
	10, // 0: rockskv.BatchGetResponse.items:type_name -> rockskv.KeyValue
	10, // 1: rockskv.BatchPutRequest.items:type_name -> rockskv.KeyValue
	0,  // 2: rockskv.StorageGetResponse.error:type_name -> rockskv.ErrorCode
	0,  // 3: rockskv.StoragePutResponse.error:type_name -> rockskv.ErrorCode
	0,  // 4: rockskv.StorageDeleteResponse.error:type_name -> rockskv.ErrorCode
	10, // 5: rockskv.StorageBatchPutRequest.items:type_name -> rockskv.KeyValue
	0,  // 6: rockskv.StorageBatchPutResponse.error:type_name -> rockskv.ErrorCode
	1,  // 7: rockskv.RegisterNodeRequest.role:type_name -> rockskv.NodeRole
	34, // 8: rockskv.GetRouteTableResponse.route_table:type_name -> rockskv.RouteTable
	35, // 9: rockskv.RouteUpdate.partitions:type_name -> rockskv.PartitionInfo
	35, // 10: rockskv.RouteTable.partitions:type_name -> rockskv.PartitionInfo
	2,  // 11: rockskv.PartitionInfo.status:type_name -> rockskv.PartitionStatus
	3,  // 12: rockskv.PartitionInfo.migration_state:type_name -> rockskv.MigrationState
	40, // 13: rockskv.GetMigrationStatusResponse.partition_status:type_name -> rockskv.PartitionMigrationStatus
	3,  // 14: rockskv.PartitionMigrationStatus.state:type_name -> rockskv.MigrationState
	4,  // 15: rockskv.KVService.Get:input_type -> rockskv.GetRequest
	6,  // 16: rockskv.KVService.Put:input_type -> rockskv.PutRequest
	8,  // 17: rockskv.KVService.Delete:input_type -> rockskv.DeleteRequest
	11, // 18: rockskv.KVService.BatchGet:input_type -> rockskv.BatchGetRequest
	13, // 19: rockskv.KVService.BatchPut:input_type -> rockskv.BatchPutRequest
	15, // 20: rockskv.StorageService.Get:input_type -> rockskv.StorageGetRequest
	17, // 21: rockskv.StorageService.Put:input_type -> rockskv.StoragePutRequest
	19, // 22: rockskv.StorageService.Delete:input_type -> rockskv.StorageDeleteRequest
	21, // 23: rockskv.StorageService.BatchPut:input_type -> rockskv.StorageBatchPutRequest
	23, // 24: rockskv.StorageService.ExportSST:input_type -> rockskv.ExportSSTRequest
	24, // 25: rockskv.StorageService.IngestSST:input_type -> rockskv.SSTChunk
	26, // 26: rockskv.MetadataService.RegisterNode:input_type -> rockskv.RegisterNodeRequest
	28, // 27: rockskv.MetadataService.Heartbeat:input_type -> rockskv.HeartbeatRequest
	30, // 28: rockskv.MetadataService.GetRouteTable:input_type -> rockskv.GetRouteTableRequest
	32, // 29: rockskv.MetadataService.SubscribeRouteUpdates:input_type -> rockskv.SubscribeRequest
	36, // 30: rockskv.MetadataService.TriggerRebalance:input_type -> rockskv.TriggerRebalanceRequest
	38, // 31: rockskv.MetadataService.GetMigrationStatus:input_type -> rockskv.GetMigrationStatusRequest
	41, // 32: rockskv.MetadataService.CancelMigration:input_type -> rockskv.CancelMigrationRequest
	5,  // 33: rockskv.KVService.Get:output_type -> rockskv.GetResponse
	7,  // 34: rockskv.KVService.Put:output_type -> rockskv.PutResponse
	9,  // 35: rockskv.KVService.Delete:output_type -> rockskv.DeleteResponse
	12, // 36: rockskv.KVService.BatchGet:output_type -> rockskv.BatchGetResponse
	14, // 37: rockskv.KVService.BatchPut:output_type -> rockskv.BatchPutResponse
	16, // 38: rockskv.StorageService.Get:output_type -> rockskv.StorageGetResponse
	18, // 39: rockskv.StorageService.Put:output_type -> rockskv.StoragePutResponse
	20, // 40: rockskv.StorageService.Delete:output_type -> rockskv.StorageDeleteResponse
	22, // 41: rockskv.StorageService.BatchPut:output_type -> rockskv.StorageBatchPutResponse
	24, // 42: rockskv.StorageService.ExportSST:output_type -> rockskv.SSTChunk
	25, // 43: rockskv.StorageService.IngestSST:output_type -> rockskv.IngestSSTResponse
	27, // 44: rockskv.MetadataService.RegisterNode:output_type -> rockskv.RegisterNodeResponse
	29, // 45: rockskv.MetadataService.Heartbeat:output_type -> rockskv.HeartbeatResponse
	31, // 46: rockskv.MetadataService.GetRouteTable:output_type -> rockskv.GetRouteTableResponse
	33, // 47: rockskv.MetadataService.SubscribeRouteUpdates:output_type -> rockskv.RouteUpdate
	37, // 48: rockskv.MetadataService.TriggerRebalance:output_type -> rockskv.TriggerRebalanceResponse
	39, // 49: rockskv.MetadataService.GetMigrationStatus:output_type -> rockskv.GetMigrationStatusResponse
	42, // 50: rockskv.MetadataService.CancelMigration:output_type -> rockskv.CancelMigrationResponse
	33, // [33:51] is the sub-list for method output_type
	15, // [15:33] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_rockskv_proto_init() }
func file_rockskv_proto_init() {
	if File_rockskv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rockskv_proto_rawDesc), len(file_rockskv_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   39,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_rockskv_proto_goTypes,
		DependencyIndexes: file_rockskv_proto_depIdxs,
		EnumInfos:         file_rockskv_proto_enumTypes,
		MessageInfos:      file_rockskv_proto_msgTypes,
	}.Build()
	File_rockskv_proto = out.File
	file_rockskv_proto_goTypes = nil
	file_rockskv_proto_depIdxs = nil
}
